### ISSUE TITLE
Will you continue to maintain node-ctypes?

### ISSUE THREAD

**Issue by ghostoy** [TooTallNate/node-ctypes#1]
There is no update since February. Looks like this module is being abandoned. Will you continue to maintain?

**Comment by TooTallNate** [comment]
Hey @ghostoy! This project did indeed fall off my radar but thanks for reminding me about it. I am definitely still maintaining it and it appears to still work on Node v6. Hopefully I'll find the time to implement some more of the features soon, and pull requests always welcome!

**Comment by ghostoy** [comment]
@TooTallNate Thank you for clarification :smiley:
